[package]
name = "fontchan-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
base64ct = { version = "1.6.0", features = ["alloc"] }
dashmap = "6.1.0"
digest = "0.10.7"
gc-arena = "0.5.3"
rayon = "1.10.0"
serde = "1.0.215"
sha2 = "0.10.8"
tempfile = "3.14.0"
